theme: jekyll-theme-cayman

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "experience"
    href:           "/experience"
  - name:           "projects"
    href:           "/projects"
  